### ISSUE TITLE
Class cast exception

### ISSUE THREAD

**Issue by Stanly-Mindssoft** [andremion/Floating-Navigation-View#2]
Process: com.andremion.floatingnavigationview.sample, PID: 28109
                                                                                             java.lang.ClassCastException: android.support.design.widget.AppBarLayout$LayoutParams cannot be cast to android.support.design.widget.CoordinatorLayout$LayoutParams
                                                                                                 at android.support.design.widget.FloatingActionButton$Behavior.isBottomSheet(FloatingActionButton.java:597)
                                                                                                 at android.support.design.widget.FloatingActionButton$Behavior.onDependentViewChanged(FloatingActionButton.java:589)
                                                                                                 at android.support.design.widget.FloatingActionButton$Behavior.onDependentViewChanged(FloatingActionButton.java:528)
                                                                                                 at android.support.design.widget.CoordinatorLayout.offsetChildToAnchor(CoordinatorLayout.java:1564)
                                                                                                 at android.support.design.widget.CoordinatorLayout.onChildViewsChanged(CoordinatorLayout.java:1233)
                                                                                                 at android.support.design.widget.CoordinatorLayout$OnPreDrawListener.onPreDraw(CoordinatorLayout.java:1812)
                                                                                                 at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:847)
                                                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1989)
                                                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1079)
                                                                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5839)
                                                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:836)
                                                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:635)
                                                                                                 at android.view.Choreographer.doFrame(Choreographer.java:601)
                                                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:822)
                                                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5318)
                                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:922)
                                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:717)

**Comment by andremion** [comment]
Could you describe how did you get this crash? What changes did you make in original source code? I need this to reproduce the issue.
Or you can make a solve so we can discuss about it.

**Comment by Stanly-Mindssoft** [comment]
https://github.com/sathishmscict/Floating-Navigation-Drawer-MEnu here is the code

**Comment by andremion** [comment]
The link is just a copy of the original repo. I can't reproduce this issue.

**Comment by Stanly-Mindssoft** [comment]
is it possible to make this library to work in Android version 4?

**Comment by Stanly-Mindssoft** [comment]
Ok Thanks...this issue can be closed too.

**Comment by Stanly-Mindssoft** [comment]
Just adding appcompat library to the gradle file crashed the entire app...

**Comment by andremion** [comment]
It doesn't make sense.  I can add any library I want and I still can't reproduce.

**Comment by andremion** [comment]
Let's close and monitor if someone else reproduce this issue. Thank you.
