### ISSUE TITLE
Doent work in android version 4

### ISSUE THREAD

**Issue by Stanly-Mindssoft** [andremion/Floating-Navigation-View#3]
android.content.res.Resources$NotFoundException: File res/drawable/ic_menu_animated.xml from drawable resource ID #0x7f020064
                                                                        at android.content.res.Resources.loadDrawable(Resources.java:3451)
                                                                        at android.content.res.Resources.getDrawable(Resources.java:1894)
                                                                        at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:354)
                                                                        at widgets.FloatingNavigationView.startOpenAnimations

Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #16: invalid drawable tag animated-vector
                                                                        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:969)
                                                                        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:913)
                                                                        at android.content.res.Resources.loadDrawable(Resources.java:3447)
                                                                        at android.content.res.Resources.getDrawable(Resources.java:1894) 
                                                                        at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:354)

**Comment by andremion** [comment]
Currently the minSdkVersion is 21.
